name: 'Repo Lockdown'

on:
  workflow_dispatch:
  issues:
    types: opened
  pull_request_target:
    types: opened
  schedule:
    - cron: '30 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
